
// Register 
export const REGISTER_USER = 'REGISTER_USER' ; 
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS' ; 
export const REGISTER_USER_FAILLURE = 'REGISTER_USER_FAILLURE' ; 
// Login 
export const LOGOUT_USER = 'LOGOUT_USER' ; 
export const LOGIN_USER = 'LOGIN_USER' ; 
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS' ; 
export const LOGIN_USER_FAILLURE = 'LOGIN_USER_FAILLURE' ; 
//login facebook
export const LOGIN_USER_FB = 'LOGIN_USER_FB' ; 
export const LOGIN_USER_SUCCESS_FB = 'LOGIN_USER_SUCCESS_FB' ; 
export const LOGIN_USER_FAILLURE_FB = 'LOGIN_USER_FAILLURE_FB' ; 
//register fb 
export const REGISTER_USER_FB = 'REGISTER_USER_FB' ; 
export const REGISTER_USER_SUCCESS_FB = 'REGISTER_USER_SUCCESS_FB' ; 
export const REGISTER_USER_FAILLURE_FB = 'REGISTER_USER_FAILLURE_FB' ; 
// Profile 
export const PROFILE_USER = 'PROFILE_USER' ; 
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS' ; 
export const PROFILE_USER_FAILLURE = 'PROFILE_USER_FAILLURE' ; 
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE' ;
export const CREATE_USER_PROFILE_SUCCESS = 'CREATE_USER_PROFILE_SUCCESS' ;
export const CREATE_USER_PROFILE_FAILLURE = 'CREATE_USER_PROFILE_FAILLURE' ;
//Send message
export const SEND_MESSAGE ="SEND_MESSAGE"
export const SEND_MESSAGE_SUCCESS ="SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILLURE ="SEND_MESSAGE_FAILLURE"
//liste users 
export const GET_USERS  ="GET_USERS"   ;
export const GET_USERS_SUCCESS ="GET_USERS_SUCCESS"
export const GET_USERS_FAILLURE ="GET_USERS_FAILLURE"
//find user by id 
export const GET_USER  ="GET_USER"   ;
export const GET_USER_SUCCESS ="GET_USER_SUCCESS"
export const GET_USER_FAILLURE ="GET_USER_FAILLURE"